locale = "zh-tw"
label = "繁體中文"
weight = 9
title = "Blowfish"

[params]
  displayName = "繁體中文"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "河豚有毒"

[params.author]
  name = "Blowfish"
  image = "img/blowfish_logo.png"
  headline = "河豚測試"
  bio = "河豚主題"
  links = [
    { x-twitter = "" },
    { github = "" },
  ]